/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../vak-app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/router/src/directives/router_link';
import * as import11 from '@angular/router/src/directives/router_outlet';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
import * as import15 from '@angular/router/src/router_outlet_map';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
import * as import17 from '@angular/core/src/security';
var renderType_VakAppComponent_Host:import0.RenderComponentType = (null as any);
class _View_VakAppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _VakAppComponent_0_4:import3.VakAppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_VakAppComponent_Host0,renderType_VakAppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('vak-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_VakAppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._VakAppComponent_0_4 = new import3.VakAppComponent();
    this._appEl_0.initComponent(this._VakAppComponent_0_4,[],compView_0);
    compView_0.create(this._VakAppComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.VakAppComponent) && (0 === requestNodeIndex))) { return this._VakAppComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_VakAppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_VakAppComponent_Host === (null as any))) { (renderType_VakAppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_VakAppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const VakAppComponentNgFactory:import9.ComponentFactory<import3.VakAppComponent> = new import9.ComponentFactory<import3.VakAppComponent>('vak-app',viewFactory_VakAppComponent_Host0,import3.VakAppComponent);
const styles_VakAppComponent:any[] = [];
var renderType_VakAppComponent:import0.RenderComponentType = (null as any);
class _View_VakAppComponent0 extends import1.AppView<import3.VakAppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import10.RouterLinkWithHref;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import2.AppElement;
  _RouterOutlet_54_5:import11.RouterOutlet;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_VakAppComponent0,renderType_VakAppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Logo',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'My VakKits',(null as any));
    this._el_6 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_8 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'My VakUnits',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_11 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_12 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this.renderer.setElementAttribute(this._el_12,'routerLink','signup');
    this._RouterLinkWithHref_12_3 = new import10.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_13 = this.renderer.createText(this._el_12,'Sign up',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Log in',(null as any));
    this._el_18 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_20 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Overview',(null as any));
    this._el_22 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_24 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'VakUnit gallery',(null as any));
    this._el_26 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_28 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Learn',(null as any));
    this._el_30 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_32 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Help',(null as any));
    this._el_34 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_36 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Account:',(null as any));
    this._el_38 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_39 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_40 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Manage account',(null as any));
    this._el_42 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_43 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_44 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n    ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'button',(null as any));
    this.renderer.setElementAttribute(this._el_46,'type','submit');
    this._text_47 = this.renderer.createText(this._el_46,'Log off',(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n',(null as any));
    this._text_49 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_50 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n    more\n',(null as any));
    this._text_52 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_53 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_54 = this.renderer.createElement(parentRenderNode,'router-outlet',(null as any));
    this._appEl_54 = new import2.AppElement(54,(null as any),this,this._el_54);
    this._RouterOutlet_54_5 = new import11.RouterOutlet(this.parentInjector.get(import15.RouterOutletMap),this._appEl_54.vcRef,this.parentInjector.get(import16.ComponentFactoryResolver),(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3; }
    if (((token === import11.RouterOutlet) && (54 === requestNodeIndex))) { return this._RouterOutlet_54_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = 'signup';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_12_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_12_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_12_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_12,'href',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_12_3.ngOnDestroy();
    this._RouterOutlet_54_5.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_12_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_VakAppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.VakAppComponent> {
  if ((renderType_VakAppComponent === (null as any))) { (renderType_VakAppComponent = viewUtils.createRenderComponentType('C:/Users/Jeremy/Documents/Visual Studio 2015/Projects/Jering.Vak/Jering.VectorArtKit.WebApplication/Angular/vak-app.html',0,import8.ViewEncapsulation.None,styles_VakAppComponent,{})); }
  return new _View_VakAppComponent0(viewUtils,parentInjector,declarationEl);
}