/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../vak-app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '../../DynamicForms/dynamic-forms.module';
import * as import10 from '../../SignUp/sign-up.module';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import24 from '@angular/http/src/backends/browser_xhr';
import * as import25 from '@angular/http/src/base_response_options';
import * as import26 from '@angular/http/src/backends/xhr_backend';
import * as import27 from '@angular/http/src/base_request_options';
import * as import28 from '@angular/forms/src/form_builder';
import * as import29 from '@angular/common/src/location/location';
import * as import30 from '@angular/router/src/url_tree';
import * as import31 from '@angular/router/src/router_outlet_map';
import * as import32 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import33 from '@angular/core/src/di/injector';
import * as import34 from './SignUp/sign-up.component.ngfactory';
import * as import35 from './vak-app.component.ngfactory';
import * as import36 from '@angular/core/src/application_tokens';
import * as import37 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import38 from '@angular/platform-browser/src/dom/events/key_events';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import41 from '../../SignUp/sign-up.component';
import * as import42 from '@angular/common/src/location/platform_location';
import * as import43 from '@angular/common/src/location/location_strategy';
import * as import44 from '@angular/router/src/router';
import * as import45 from '@angular/core/src/console';
import * as import46 from '@angular/core/src/i18n/tokens';
import * as import47 from '@angular/core/src/error_handler';
import * as import48 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import49 from '@angular/platform-browser/src/dom/animation_driver';
import * as import50 from '@angular/core/src/render/api';
import * as import51 from '@angular/core/src/security';
import * as import52 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import53 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import54 from '@angular/http/src/interfaces';
import * as import55 from '@angular/http/src/http';
import * as import56 from '@angular/router/src/router_config_loader';
import * as import57 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import58 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _ReactiveFormsModule_8:import6.ReactiveFormsModule;
  _DynamicFormsModule_9:import9.DynamicFormsModule;
  _SignUpModule_10:import10.SignUpModule;
  _AppModule_11:import1.AppModule;
  __LOCALE_ID_12:any;
  __NgLocalization_13:import11.NgLocaleLocalization;
  _ErrorHandler_14:any;
  _ApplicationInitStatus_15:import12.ApplicationInitStatus;
  _Testability_16:import13.Testability;
  _ApplicationRef__17:import14.ApplicationRef_;
  __ApplicationRef_18:any;
  __Compiler_19:import15.Compiler;
  __APP_ID_20:any;
  __DOCUMENT_21:any;
  __HAMMER_GESTURE_CONFIG_22:import16.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_23:any[];
  __EventManager_24:import17.EventManager;
  __DomSharedStylesHost_25:import18.DomSharedStylesHost;
  __AnimationDriver_26:any;
  __DomRootRenderer_27:import19.DomRootRenderer_;
  __RootRenderer_28:any;
  __DomSanitizer_29:import20.DomSanitizerImpl;
  __Sanitizer_30:any;
  __ViewUtils_31:import21.ViewUtils;
  __IterableDiffers_32:any;
  __KeyValueDiffers_33:any;
  __SharedStylesHost_34:any;
  __Title_35:import22.Title;
  __RadioControlRegistry_36:import23.RadioControlRegistry;
  __BrowserXhr_37:import24.BrowserXhr;
  __ResponseOptions_38:import25.BaseResponseOptions;
  __XSRFStrategy_39:any;
  __XHRBackend_40:import26.XHRBackend;
  __RequestOptions_41:import27.BaseRequestOptions;
  __Http_42:any;
  __FormBuilder_43:import28.FormBuilder;
  __ROUTES_44:any[];
  __ROUTER_CONFIGURATION_45:any;
  __LocationStrategy_46:any;
  __Location_47:import29.Location;
  __UrlSerializer_48:import30.DefaultUrlSerializer;
  __RouterOutletMap_49:import31.RouterOutletMap;
  __NgModuleFactoryLoader_50:import32.SystemJsNgModuleLoader;
  __Router_51:any;
  __ActivatedRoute_52:any;
  __APP_BOOTSTRAP_LISTENER_53:any[];
  constructor(parent:import33.Injector) {
    super(parent,[
      import34.SignUpComponentNgFactory,
      import35.VakAppComponentNgFactory
    ]
    ,[import35.VakAppComponentNgFactory]);
  }
  get _LOCALE_ID_12():any {
    if ((this.__LOCALE_ID_12 == (null as any))) { (this.__LOCALE_ID_12 = 'en-US'); }
    return this.__LOCALE_ID_12;
  }
  get _NgLocalization_13():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_13 == (null as any))) { (this.__NgLocalization_13 = new import11.NgLocaleLocalization(this._LOCALE_ID_12)); }
    return this.__NgLocalization_13;
  }
  get _ApplicationRef_18():any {
    if ((this.__ApplicationRef_18 == (null as any))) { (this.__ApplicationRef_18 = this._ApplicationRef__17); }
    return this.__ApplicationRef_18;
  }
  get _Compiler_19():import15.Compiler {
    if ((this.__Compiler_19 == (null as any))) { (this.__Compiler_19 = new import15.Compiler()); }
    return this.__Compiler_19;
  }
  get _APP_ID_20():any {
    if ((this.__APP_ID_20 == (null as any))) { (this.__APP_ID_20 = import36._appIdRandomProviderFactory()); }
    return this.__APP_ID_20;
  }
  get _DOCUMENT_21():any {
    if ((this.__DOCUMENT_21 == (null as any))) { (this.__DOCUMENT_21 = import4._document()); }
    return this.__DOCUMENT_21;
  }
  get _HAMMER_GESTURE_CONFIG_22():import16.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_22 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_22 = new import16.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_22;
  }
  get _EVENT_MANAGER_PLUGINS_23():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_23 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_23 = [
      new import37.DomEventsPlugin(),
      new import38.KeyEventsPlugin(),
      new import16.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_22)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_23;
  }
  get _EventManager_24():import17.EventManager {
    if ((this.__EventManager_24 == (null as any))) { (this.__EventManager_24 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_23,this.parent.get(import39.NgZone))); }
    return this.__EventManager_24;
  }
  get _DomSharedStylesHost_25():import18.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_25 == (null as any))) { (this.__DomSharedStylesHost_25 = new import18.DomSharedStylesHost(this._DOCUMENT_21)); }
    return this.__DomSharedStylesHost_25;
  }
  get _AnimationDriver_26():any {
    if ((this.__AnimationDriver_26 == (null as any))) { (this.__AnimationDriver_26 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_26;
  }
  get _DomRootRenderer_27():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_27 == (null as any))) { (this.__DomRootRenderer_27 = new import19.DomRootRenderer_(this._DOCUMENT_21,this._EventManager_24,this._DomSharedStylesHost_25,this._AnimationDriver_26)); }
    return this.__DomRootRenderer_27;
  }
  get _RootRenderer_28():any {
    if ((this.__RootRenderer_28 == (null as any))) { (this.__RootRenderer_28 = import40._createConditionalRootRenderer(this._DomRootRenderer_27,this.parent.get(import40.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_28;
  }
  get _DomSanitizer_29():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_29 == (null as any))) { (this.__DomSanitizer_29 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_29;
  }
  get _Sanitizer_30():any {
    if ((this.__Sanitizer_30 == (null as any))) { (this.__Sanitizer_30 = this._DomSanitizer_29); }
    return this.__Sanitizer_30;
  }
  get _ViewUtils_31():import21.ViewUtils {
    if ((this.__ViewUtils_31 == (null as any))) { (this.__ViewUtils_31 = new import21.ViewUtils(this._RootRenderer_28,this._APP_ID_20,this._Sanitizer_30)); }
    return this.__ViewUtils_31;
  }
  get _IterableDiffers_32():any {
    if ((this.__IterableDiffers_32 == (null as any))) { (this.__IterableDiffers_32 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_32;
  }
  get _KeyValueDiffers_33():any {
    if ((this.__KeyValueDiffers_33 == (null as any))) { (this.__KeyValueDiffers_33 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_33;
  }
  get _SharedStylesHost_34():any {
    if ((this.__SharedStylesHost_34 == (null as any))) { (this.__SharedStylesHost_34 = this._DomSharedStylesHost_25); }
    return this.__SharedStylesHost_34;
  }
  get _Title_35():import22.Title {
    if ((this.__Title_35 == (null as any))) { (this.__Title_35 = new import22.Title()); }
    return this.__Title_35;
  }
  get _RadioControlRegistry_36():import23.RadioControlRegistry {
    if ((this.__RadioControlRegistry_36 == (null as any))) { (this.__RadioControlRegistry_36 = new import23.RadioControlRegistry()); }
    return this.__RadioControlRegistry_36;
  }
  get _BrowserXhr_37():import24.BrowserXhr {
    if ((this.__BrowserXhr_37 == (null as any))) { (this.__BrowserXhr_37 = new import24.BrowserXhr()); }
    return this.__BrowserXhr_37;
  }
  get _ResponseOptions_38():import25.BaseResponseOptions {
    if ((this.__ResponseOptions_38 == (null as any))) { (this.__ResponseOptions_38 = new import25.BaseResponseOptions()); }
    return this.__ResponseOptions_38;
  }
  get _XSRFStrategy_39():any {
    if ((this.__XSRFStrategy_39 == (null as any))) { (this.__XSRFStrategy_39 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_39;
  }
  get _XHRBackend_40():import26.XHRBackend {
    if ((this.__XHRBackend_40 == (null as any))) { (this.__XHRBackend_40 = new import26.XHRBackend(this._BrowserXhr_37,this._ResponseOptions_38,this._XSRFStrategy_39)); }
    return this.__XHRBackend_40;
  }
  get _RequestOptions_41():import27.BaseRequestOptions {
    if ((this.__RequestOptions_41 == (null as any))) { (this.__RequestOptions_41 = new import27.BaseRequestOptions()); }
    return this.__RequestOptions_41;
  }
  get _Http_42():any {
    if ((this.__Http_42 == (null as any))) { (this.__Http_42 = import7.httpFactory(this._XHRBackend_40,this._RequestOptions_41)); }
    return this.__Http_42;
  }
  get _FormBuilder_43():import28.FormBuilder {
    if ((this.__FormBuilder_43 == (null as any))) { (this.__FormBuilder_43 = new import28.FormBuilder()); }
    return this.__FormBuilder_43;
  }
  get _ROUTES_44():any[] {
    if ((this.__ROUTES_44 == (null as any))) { (this.__ROUTES_44 = [
        [{
          path: 'signup',
          component: import41.SignUpComponent
        }
      ],
      []
    ]
    ); }
    return this.__ROUTES_44;
  }
  get _ROUTER_CONFIGURATION_45():any {
    if ((this.__ROUTER_CONFIGURATION_45 == (null as any))) { (this.__ROUTER_CONFIGURATION_45 = {}); }
    return this.__ROUTER_CONFIGURATION_45;
  }
  get _LocationStrategy_46():any {
    if ((this.__LocationStrategy_46 == (null as any))) { (this.__LocationStrategy_46 = import8.provideLocationStrategy(this.parent.get(import42.PlatformLocation),this.parent.get(import43.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_45)); }
    return this.__LocationStrategy_46;
  }
  get _Location_47():import29.Location {
    if ((this.__Location_47 == (null as any))) { (this.__Location_47 = new import29.Location(this._LocationStrategy_46)); }
    return this.__Location_47;
  }
  get _UrlSerializer_48():import30.DefaultUrlSerializer {
    if ((this.__UrlSerializer_48 == (null as any))) { (this.__UrlSerializer_48 = new import30.DefaultUrlSerializer()); }
    return this.__UrlSerializer_48;
  }
  get _RouterOutletMap_49():import31.RouterOutletMap {
    if ((this.__RouterOutletMap_49 == (null as any))) { (this.__RouterOutletMap_49 = new import31.RouterOutletMap()); }
    return this.__RouterOutletMap_49;
  }
  get _NgModuleFactoryLoader_50():import32.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_50 == (null as any))) { (this.__NgModuleFactoryLoader_50 = new import32.SystemJsNgModuleLoader(this._Compiler_19,this.parent.get(import32.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_50;
  }
  get _Router_51():any {
    if ((this.__Router_51 == (null as any))) { (this.__Router_51 = import8.setupRouter(this._ApplicationRef_18,this._UrlSerializer_48,this._RouterOutletMap_49,this._Location_47,this,this._NgModuleFactoryLoader_50,this._Compiler_19,this._ROUTES_44,this._ROUTER_CONFIGURATION_45)); }
    return this.__Router_51;
  }
  get _ActivatedRoute_52():any {
    if ((this.__ActivatedRoute_52 == (null as any))) { (this.__ActivatedRoute_52 = import8.rootRoute(this._Router_51)); }
    return this.__ActivatedRoute_52;
  }
  get _APP_BOOTSTRAP_LISTENER_53():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_53 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_53 = [import8.initialRouterNavigation(this._Router_51,this._ROUTER_CONFIGURATION_45)]); }
    return this.__APP_BOOTSTRAP_LISTENER_53;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import44.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._ReactiveFormsModule_8 = new import6.ReactiveFormsModule();
    this._DynamicFormsModule_9 = new import9.DynamicFormsModule();
    this._SignUpModule_10 = new import10.SignUpModule();
    this._AppModule_11 = new import1.AppModule();
    this._ErrorHandler_14 = import4.errorHandler();
    this._ApplicationInitStatus_15 = new import12.ApplicationInitStatus(this.parent.get(import12.APP_INITIALIZER,(null as any)));
    this._Testability_16 = new import13.Testability(this.parent.get(import39.NgZone));
    this._ApplicationRef__17 = new import14.ApplicationRef_(this.parent.get(import39.NgZone),this.parent.get(import45.Console),this,this._ErrorHandler_14,this,this._ApplicationInitStatus_15,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_16);
    return this._AppModule_11;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_8; }
    if ((token === import9.DynamicFormsModule)) { return this._DynamicFormsModule_9; }
    if ((token === import10.SignUpModule)) { return this._SignUpModule_10; }
    if ((token === import1.AppModule)) { return this._AppModule_11; }
    if ((token === import46.LOCALE_ID)) { return this._LOCALE_ID_12; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_13; }
    if ((token === import47.ErrorHandler)) { return this._ErrorHandler_14; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_15; }
    if ((token === import13.Testability)) { return this._Testability_16; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__17; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_18; }
    if ((token === import15.Compiler)) { return this._Compiler_19; }
    if ((token === import36.APP_ID)) { return this._APP_ID_20; }
    if ((token === import48.DOCUMENT)) { return this._DOCUMENT_21; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_22; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_23; }
    if ((token === import17.EventManager)) { return this._EventManager_24; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_25; }
    if ((token === import49.AnimationDriver)) { return this._AnimationDriver_26; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_27; }
    if ((token === import50.RootRenderer)) { return this._RootRenderer_28; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_29; }
    if ((token === import51.Sanitizer)) { return this._Sanitizer_30; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_31; }
    if ((token === import52.IterableDiffers)) { return this._IterableDiffers_32; }
    if ((token === import53.KeyValueDiffers)) { return this._KeyValueDiffers_33; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_34; }
    if ((token === import22.Title)) { return this._Title_35; }
    if ((token === import23.RadioControlRegistry)) { return this._RadioControlRegistry_36; }
    if ((token === import24.BrowserXhr)) { return this._BrowserXhr_37; }
    if ((token === import25.ResponseOptions)) { return this._ResponseOptions_38; }
    if ((token === import54.XSRFStrategy)) { return this._XSRFStrategy_39; }
    if ((token === import26.XHRBackend)) { return this._XHRBackend_40; }
    if ((token === import27.RequestOptions)) { return this._RequestOptions_41; }
    if ((token === import55.Http)) { return this._Http_42; }
    if ((token === import28.FormBuilder)) { return this._FormBuilder_43; }
    if ((token === import56.ROUTES)) { return this._ROUTES_44; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_45; }
    if ((token === import43.LocationStrategy)) { return this._LocationStrategy_46; }
    if ((token === import29.Location)) { return this._Location_47; }
    if ((token === import30.UrlSerializer)) { return this._UrlSerializer_48; }
    if ((token === import31.RouterOutletMap)) { return this._RouterOutletMap_49; }
    if ((token === import57.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_50; }
    if ((token === import44.Router)) { return this._Router_51; }
    if ((token === import58.ActivatedRoute)) { return this._ActivatedRoute_52; }
    if ((token === import36.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_53; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__17.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);