/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../SignUp/sign-up.module';
import * as import2 from '@angular/forms/src/directives';
import * as import3 from '@angular/forms/src/form_providers';
import * as import4 from '@angular/http/src/http_module';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '@angular/common/src/common_module';
import * as import7 from '../../../DynamicForms/dynamic-forms.module';
import * as import8 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import9 from '@angular/http/src/backends/browser_xhr';
import * as import10 from '@angular/http/src/base_response_options';
import * as import11 from '@angular/http/src/backends/xhr_backend';
import * as import12 from '@angular/http/src/base_request_options';
import * as import13 from '@angular/common/src/localization';
import * as import14 from '@angular/forms/src/form_builder';
import * as import15 from '@angular/core/src/di/injector';
import * as import16 from './sign-up.component.ngfactory';
import * as import17 from '@angular/core/src/i18n/tokens';
import * as import18 from '../../../SignUp/sign-up.component';
import * as import19 from '@angular/http/src/interfaces';
import * as import20 from '@angular/http/src/http';
import * as import21 from '@angular/router/src/router_config_loader';
class SignUpModuleInjector extends import0.NgModuleInjector<import1.SignUpModule> {
  _InternalFormsSharedModule_0:import2.InternalFormsSharedModule;
  _FormsModule_1:import3.FormsModule;
  _HttpModule_2:import4.HttpModule;
  _RouterModule_3:import5.RouterModule;
  _CommonModule_4:import6.CommonModule;
  _ReactiveFormsModule_5:import3.ReactiveFormsModule;
  _DynamicFormsModule_6:import7.DynamicFormsModule;
  _SignUpModule_7:import1.SignUpModule;
  __RadioControlRegistry_8:import8.RadioControlRegistry;
  __BrowserXhr_9:import9.BrowserXhr;
  __ResponseOptions_10:import10.BaseResponseOptions;
  __XSRFStrategy_11:any;
  __XHRBackend_12:import11.XHRBackend;
  __RequestOptions_13:import12.BaseRequestOptions;
  __Http_14:any;
  __NgLocalization_15:import13.NgLocaleLocalization;
  __FormBuilder_16:import14.FormBuilder;
  __ROUTES_17:any[];
  constructor(parent:import15.Injector) {
    super(parent,[import16.SignUpComponentNgFactory],[]);
  }
  get _RadioControlRegistry_8():import8.RadioControlRegistry {
    if ((this.__RadioControlRegistry_8 == (null as any))) { (this.__RadioControlRegistry_8 = new import8.RadioControlRegistry()); }
    return this.__RadioControlRegistry_8;
  }
  get _BrowserXhr_9():import9.BrowserXhr {
    if ((this.__BrowserXhr_9 == (null as any))) { (this.__BrowserXhr_9 = new import9.BrowserXhr()); }
    return this.__BrowserXhr_9;
  }
  get _ResponseOptions_10():import10.BaseResponseOptions {
    if ((this.__ResponseOptions_10 == (null as any))) { (this.__ResponseOptions_10 = new import10.BaseResponseOptions()); }
    return this.__ResponseOptions_10;
  }
  get _XSRFStrategy_11():any {
    if ((this.__XSRFStrategy_11 == (null as any))) { (this.__XSRFStrategy_11 = import4._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_11;
  }
  get _XHRBackend_12():import11.XHRBackend {
    if ((this.__XHRBackend_12 == (null as any))) { (this.__XHRBackend_12 = new import11.XHRBackend(this._BrowserXhr_9,this._ResponseOptions_10,this._XSRFStrategy_11)); }
    return this.__XHRBackend_12;
  }
  get _RequestOptions_13():import12.BaseRequestOptions {
    if ((this.__RequestOptions_13 == (null as any))) { (this.__RequestOptions_13 = new import12.BaseRequestOptions()); }
    return this.__RequestOptions_13;
  }
  get _Http_14():any {
    if ((this.__Http_14 == (null as any))) { (this.__Http_14 = import4.httpFactory(this._XHRBackend_12,this._RequestOptions_13)); }
    return this.__Http_14;
  }
  get _NgLocalization_15():import13.NgLocaleLocalization {
    if ((this.__NgLocalization_15 == (null as any))) { (this.__NgLocalization_15 = new import13.NgLocaleLocalization(this.parent.get(import17.LOCALE_ID))); }
    return this.__NgLocalization_15;
  }
  get _FormBuilder_16():import14.FormBuilder {
    if ((this.__FormBuilder_16 == (null as any))) { (this.__FormBuilder_16 = new import14.FormBuilder()); }
    return this.__FormBuilder_16;
  }
  get _ROUTES_17():any[] {
        if ((this.__ROUTES_17 == (null as any))) { (this.__ROUTES_17 = [[{
          path: 'signup',
          component: import18.SignUpComponent
        }
    ]]); }
    return this.__ROUTES_17;
  }
  createInternal():import1.SignUpModule {
    this._InternalFormsSharedModule_0 = new import2.InternalFormsSharedModule();
    this._FormsModule_1 = new import3.FormsModule();
    this._HttpModule_2 = new import4.HttpModule();
    this._RouterModule_3 = new import5.RouterModule(this.parent.get(import5.ROUTER_FORROOT_GUARD,(null as any)));
    this._CommonModule_4 = new import6.CommonModule();
    this._ReactiveFormsModule_5 = new import3.ReactiveFormsModule();
    this._DynamicFormsModule_6 = new import7.DynamicFormsModule();
    this._SignUpModule_7 = new import1.SignUpModule();
    return this._SignUpModule_7;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_0; }
    if ((token === import3.FormsModule)) { return this._FormsModule_1; }
    if ((token === import4.HttpModule)) { return this._HttpModule_2; }
    if ((token === import5.RouterModule)) { return this._RouterModule_3; }
    if ((token === import6.CommonModule)) { return this._CommonModule_4; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import7.DynamicFormsModule)) { return this._DynamicFormsModule_6; }
    if ((token === import1.SignUpModule)) { return this._SignUpModule_7; }
    if ((token === import8.RadioControlRegistry)) { return this._RadioControlRegistry_8; }
    if ((token === import9.BrowserXhr)) { return this._BrowserXhr_9; }
    if ((token === import10.ResponseOptions)) { return this._ResponseOptions_10; }
    if ((token === import19.XSRFStrategy)) { return this._XSRFStrategy_11; }
    if ((token === import11.XHRBackend)) { return this._XHRBackend_12; }
    if ((token === import12.RequestOptions)) { return this._RequestOptions_13; }
    if ((token === import20.Http)) { return this._Http_14; }
    if ((token === import13.NgLocalization)) { return this._NgLocalization_15; }
    if ((token === import14.FormBuilder)) { return this._FormBuilder_16; }
    if ((token === import21.ROUTES)) { return this._ROUTES_17; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SignUpModuleNgFactory:import0.NgModuleFactory<import1.SignUpModule> = new import0.NgModuleFactory(SignUpModuleInjector,import1.SignUpModule);