/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../SignUp/sign-up.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../../DynamicForms/dynamic-forms.service';
import * as import11 from '../../../DynamicForms/dynamic-form.component';
import * as import12 from '../DynamicForms/dynamic-form.component.ngfactory';
import * as import13 from '@angular/http/src/http';
var renderType_SignUpComponent_Host:import0.RenderComponentType = (null as any);
class _View_SignUpComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SignUpComponent_0_4:import3.SignUpComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpComponent_Host0,renderType_SignUpComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignUpComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignUpComponent_0_4 = new import3.SignUpComponent();
    this._appEl_0.initComponent(this._SignUpComponent_0_4,[],compView_0);
    compView_0.create(this._SignUpComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SignUpComponent) && (0 === requestNodeIndex))) { return this._SignUpComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SignUpComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SignUpComponent_Host === (null as any))) { (renderType_SignUpComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_SignUpComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignUpComponentNgFactory:import9.ComponentFactory<import3.SignUpComponent> = new import9.ComponentFactory<import3.SignUpComponent>('ng-component',viewFactory_SignUpComponent_Host0,import3.SignUpComponent);
const styles_SignUpComponent:any[] = [];
var renderType_SignUpComponent:import0.RenderComponentType = (null as any);
class _View_SignUpComponent0 extends import1.AppView<import3.SignUpComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _DynamicFormsService_6_4:import10.DynamicFormsService;
  _DynamicFormComponent_6_5:import11.DynamicFormComponent;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignUpComponent0,renderType_SignUpComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h2',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Sign Up',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    logo\n',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_6 = this.renderer.createElement(parentRenderNode,'dynamic-form',(null as any));
    this._appEl_6 = new import2.AppElement(6,(null as any),this,this._el_6);
    var compView_6:any = import12.viewFactory_DynamicFormComponent0(this.viewUtils,this.injector(6),this._appEl_6);
    this._DynamicFormsService_6_4 = new import10.DynamicFormsService(this.parentInjector.get(import13.Http));
    this._DynamicFormComponent_6_5 = new import11.DynamicFormComponent(this._DynamicFormsService_6_4);
    this._appEl_6.initComponent(this._DynamicFormComponent_6_5,[],compView_6);
    compView_6.create(this._DynamicFormComponent_6_5,[],(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DynamicFormsService) && (6 === requestNodeIndex))) { return this._DynamicFormsService_6_4; }
    if (((token === import11.DynamicFormComponent) && (6 === requestNodeIndex))) { return this._DynamicFormComponent_6_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.formModelName;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._DynamicFormComponent_6_5.formModelName = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._DynamicFormComponent_6_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_SignUpComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SignUpComponent> {
  if ((renderType_SignUpComponent === (null as any))) { (renderType_SignUpComponent = viewUtils.createRenderComponentType('C:/Users/Jeremy/Documents/Visual Studio 2015/Projects/Jering.Vak/Jering.VectorArtKit.WebApplication/Angular/SignUp/sign-up.html',0,import8.ViewEncapsulation.None,styles_SignUpComponent,{})); }
  return new _View_SignUpComponent0(viewUtils,parentInjector,declarationEl);
}