//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jering.VectorArtKit.WebApi.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jering.VectorArtKit.WebApi.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Alternative email address.
        /// </summary>
        public static string DisplayName_AlternativeEmail {
            get {
                return ResourceManager.GetString("DisplayName_AlternativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string DisplayName_ConfirmPassword {
            get {
                return ResourceManager.GetString("DisplayName_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Display name.
        /// </summary>
        public static string DisplayName_DisplayName {
            get {
                return ResourceManager.GetString("DisplayName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email address.
        /// </summary>
        public static string DisplayName_Email {
            get {
                return ResourceManager.GetString("DisplayName_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password.
        /// </summary>
        public static string DisplayName_Password {
            get {
                return ResourceManager.GetString("DisplayName_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string DisplayName_RememberMe {
            get {
                return ResourceManager.GetString("DisplayName_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Two factor authentication.
        /// </summary>
        public static string DisplayName_TwoFactor {
            get {
                return ResourceManager.GetString("DisplayName_TwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please confirm your email by clicking this link: &lt;a href=&quot;{0}&quot;&gt;link&lt;/a&gt;.
        /// </summary>
        public static string Email_EmailVerification_Message {
            get {
                return ResourceManager.GetString("Email_EmailVerification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string Email_EmailVerification_Subject {
            get {
                return ResourceManager.GetString("Email_EmailVerification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password confirmation does not match password..
        /// </summary>
        public static string ErrorMessage_ConfirmPassword_Differs {
            get {
                return ResourceManager.GetString("ErrorMessage_ConfirmPassword_Differs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password confirmation is required..
        /// </summary>
        public static string ErrorMessage_ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid current password.
        /// </summary>
        public static string ErrorMessage_CurrentPassword_Invalid {
            get {
                return ResourceManager.GetString("ErrorMessage_CurrentPassword_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Display name must have at least 2 characters..
        /// </summary>
        public static string ErrorMessage_DisplayName_FormatInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayName_FormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Display name already in use by another account..
        /// </summary>
        public static string ErrorMessage_DisplayName_InUse {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayName_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email already in use by another account..
        /// </summary>
        public static string ErrorMessage_Email_InUse {
            get {
                return ResourceManager.GetString("ErrorMessage_Email_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string ErrorMessage_Email_Invalid {
            get {
                return ResourceManager.GetString("ErrorMessage_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string ErrorMessage_Email_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Form has invalid fields..
        /// </summary>
        public static string ErrorMessage_Form_Invalid {
            get {
                return ResourceManager.GetString("ErrorMessage_Form_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string ErrorMessage_LogIn_Failed {
            get {
                return ResourceManager.GetString("ErrorMessage_LogIn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New display name cannot be the same as current display name..
        /// </summary>
        public static string ErrorMessage_NewDisplayName_MustDiffer {
            get {
                return ResourceManager.GetString("ErrorMessage_NewDisplayName_MustDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New email cannot be the same as current email..
        /// </summary>
        public static string ErrorMessage_NewEmail_MustDiffer {
            get {
                return ResourceManager.GetString("ErrorMessage_NewEmail_MustDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password must be at least 8 characters long. New password must include both upper and lower case characters. New password cannot be the same as current password..
        /// </summary>
        public static string ErrorMessage_NewPassword_FormatInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_NewPassword_FormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password cannot bt the same as current password..
        /// </summary>
        public static string ErrorMessage_NewPassword_MustDiffer {
            get {
                return ResourceManager.GetString("ErrorMessage_NewPassword_MustDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string ErrorMessage_Password_Invalid {
            get {
                return ResourceManager.GetString("ErrorMessage_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password is required..
        /// </summary>
        public static string ErrorMessage_Password_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must include at least 1 lower case character..
        /// </summary>
        public static string ErrorMessage_Password_RequiresLowerCase {
            get {
                return ResourceManager.GetString("ErrorMessage_Password_RequiresLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must include at least 1 upper case character..
        /// </summary>
        public static string ErrorMessage_Password_RequiresUpperCase {
            get {
                return ResourceManager.GetString("ErrorMessage_Password_RequiresUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string ErrorMessage_Password_TooShort {
            get {
                return ResourceManager.GetString("ErrorMessage_Password_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password too simple..
        /// </summary>
        public static string ErrorMessage_Password_TooSimple {
            get {
                return ResourceManager.GetString("ErrorMessage_Password_TooSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string ErrorMessage_TwoFactorCode_Invalid {
            get {
                return ResourceManager.GetString("ErrorMessage_TwoFactorCode_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string ErrorMessage_UnexpectedError {
            get {
                return ResourceManager.GetString("ErrorMessage_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please reset your email at this link: &lt;a href=&quot;{0}&quot;&gt;link&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordEmail_Message {
            get {
                return ResourceManager.GetString("ResetPasswordEmail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordEmail_Subject {
            get {
                return ResourceManager.GetString("ResetPasswordEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An email has been sent to {0}..
        /// </summary>
        public static string SendTwoFactorCode_EmailSent {
            get {
                return ResourceManager.GetString("SendTwoFactorCode_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your code is: {0}.
        /// </summary>
        public static string TwoFactorEmail_Message {
            get {
                return ResourceManager.GetString("TwoFactorEmail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Two factor code.
        /// </summary>
        public static string TwoFactorEmail_Subject {
            get {
                return ResourceManager.GetString("TwoFactorEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Alternative email verification confirmation.
        /// </summary>
        public static string ViewTitle_AlternativeEmailVerificationConfirmation {
            get {
                return ResourceManager.GetString("ViewTitle_AlternativeEmailVerificationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Change alternative email.
        /// </summary>
        public static string ViewTitle_ChangeAlternativeEmail {
            get {
                return ResourceManager.GetString("ViewTitle_ChangeAlternativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Change display name.
        /// </summary>
        public static string ViewTitle_ChangeDisplayName {
            get {
                return ResourceManager.GetString("ViewTitle_ChangeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Change email.
        /// </summary>
        public static string ViewTitle_ChangeEmail {
            get {
                return ResourceManager.GetString("ViewTitle_ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Change password.
        /// </summary>
        public static string ViewTitle_ChangePassword {
            get {
                return ResourceManager.GetString("ViewTitle_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email verification confirmation.
        /// </summary>
        public static string ViewTitle_EmailVerificationConfirmation {
            get {
                return ResourceManager.GetString("ViewTitle_EmailVerificationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error.
        /// </summary>
        public static string ViewTitle_Error {
            get {
                return ResourceManager.GetString("ViewTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ViewTitle_ForgotPassword {
            get {
                return ResourceManager.GetString("ViewTitle_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string ViewTitle_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ViewTitle_ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Log in.
        /// </summary>
        public static string ViewTitle_LogIn {
            get {
                return ResourceManager.GetString("ViewTitle_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Manage account.
        /// </summary>
        public static string ViewTitle_ManageAccount {
            get {
                return ResourceManager.GetString("ViewTitle_ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ViewTitle_ResetPassword {
            get {
                return ResourceManager.GetString("ViewTitle_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ViewTitle_ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ViewTitle_ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Send email verification email confirmation.
        /// </summary>
        public static string ViewTitle_SendEmailVerificationEmailConfirmation {
            get {
                return ResourceManager.GetString("ViewTitle_SendEmailVerificationEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign up.
        /// </summary>
        public static string ViewTitle_SignUp {
            get {
                return ResourceManager.GetString("ViewTitle_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Test two factor authentication.
        /// </summary>
        public static string ViewTitle_TestTwoFactor {
            get {
                return ResourceManager.GetString("ViewTitle_TestTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Verify two factor code.
        /// </summary>
        public static string ViewTitle_VerifyTwoFactorCode {
            get {
                return ResourceManager.GetString("ViewTitle_VerifyTwoFactorCode", resourceCulture);
            }
        }
    }
}
